%%{init: {'theme':'base','themeVariables':{ 'primaryColor':'#e0f2fe', 'primaryTextColor':'#0c4a6e', 'primaryBorderColor':'#0284c7', 'lineColor':'#334155' }}}%%
C4Context
title Sistema de Evaluacion Universitaria - Contexto
LAYOUT_TOP_DOWN()

Person(docente, "Docente", "Opera el panel local")
Person(alumno, "Alumno", "Consulta resultados")
System_Boundary(local, "Entorno local") {
  System(webDoc, "Web Docente", "React + Vite")
  System(apiDoc, "API Docente", "Express + TypeScript")
}
System_Boundary(cloud, "Nube") {
  System(webAlu, "Web Alumno", "React app_alumno")
  System(apiPortal, "API Portal Alumno", "Express + TypeScript")
  SystemDb(mongoCloud, "MongoDB Cloud", "Resultados y sesiones")
}
SystemDb(mongoLocal, "MongoDB Local", "Datos docentes")
System_Ext(pdfStore, "PDFs locales", "data/examenes")
System_Ext(mail, "Correo", "Opcional")

Rel_D(docente, webDoc, "Usa", "HTTP")
Rel_D(webDoc, apiDoc, "Consume API", "JSON")
Rel_D(apiDoc, mongoLocal, "CRUD")
Rel_R(apiDoc, pdfStore, "Genera y lee")
Rel_R(apiDoc, mail, "Envia codigo", "SMTP")
Rel_D(apiDoc, apiPortal, "Publica resultados", "HTTP + API Key")
Rel_D(alumno, webAlu, "Consulta", "HTTP")
Rel_D(webAlu, apiPortal, "Consume API", "JSON")
Rel_D(apiPortal, mongoCloud, "CRUD")