%%{init: {'flowchart': {'curve': 'basis', 'nodeSpacing': 50, 'rankSpacing': 60}}}%%
flowchart TD
  A[Docente crea periodo y alumnos] --> B[Docente crea banco de preguntas]
  B --> C[Crear plantilla de examen]
  C --> D[Generar examen + PDF + QR]
  D --> E[Entrega y vinculacion de folio-alumno]
  E --> F[Escaneo OMR]
  F --> G[Calificar examen]
  G --> H[Analiticas + exportar CSV]
  G --> I[Publicar resultados al portal]
  I --> J[Alumno consulta resultados y PDF]